const projects = [
  {
    title: "SILT Middelkerke",
    description: "Middelkerke, Belgium",
    mediaType: "image",
    mediaSrc: "/projects/SILTMiddelkerke/images/Full/1.png",
    targetUrl: "/SILTMiddelkerke",
    categories: ["Computational Design"],
  },
  {
    title: "Four Seasons Facade",
    description: "Dubai,UAE",
    mediaType: "image",
    mediaSrc:
      "/projects/Four Seasons Facade System/images/diagram 11-Photoshopped.png",
    targetUrl: "/FourSeasonsFacade",
    categories: ["Architecture"],
    invert: true,
  },
  {
    title: "ECHO",
    description: "Sinop,Turkey",
    mediaType: "image",
    mediaSrc: "/projects/ECHO/images/Arch System-logo.png",
    targetUrl: "/ECHO",
    categories: ["Architecture"],
  },
  {
    title: "APE Tools",
    description: "Description of Ape Tools",
    mediaType: "image",
    mediaSrc: "/path/to/ape-tools-image.jpg",
    targetUrl: "/APETools",
    categories: ["Computational Design", "Software Development"],
  },
  {
    title: "Cliff Youth Center",
    description: "Description of Cliff Youth Center",
    mediaType: "image",
    mediaSrc: "/projects/Cliff Youth Center/images/ArchSystemIcon.png",
    targetUrl: "/CliffYouthCenter",
    categories: ["Architecture"],
  },
  {
    title: "4D Droplets Clash",
    description: "Basic Abstraction Design",
    mediaType: "image",
    mediaSrc: "/projects/Droplets Clash/images/mix 1t.jpg",
    targetUrl: "/Droplets Clash",
    categories: ["Abstract Art"],
    invert: true,
  },
  {
    title: "Cowes Week Pavilion",
    description: "Description of Cowes Week Pavilion",
    mediaType: "image",
    mediaSrc: "/projects/Cowes Week Pavilion/images/robot 2.png",
    targetUrl: "CowesWeekPavilion",
    categories: ["Computational Design", "Architecture"],
  },
  {
    title: "Algorithm for Local Facade Geometries",
    description: "GENx Facade Solution",
    mediaType: "image",
    mediaSrc: "/projects/GENx Facade Solution/images/combined.jpg",
    targetUrl: "/GENxFacadeSolution",
    categories: ["Computational Design", "Software Development"],
    invert: true,
  },

  {
    title: "WEAVE",
    description: "The Extinction Museum",
    mediaType: "image",
    mediaSrc: "/projects/WEAVE/images/exploded.jpg",
    targetUrl: "/WEAVE",
    categories: ["Architecture"],
    invert: true,
  },
  {
    title: "VOX Exporter",
    description: "Direct link to MagicaVoxel through the APE Plugin",
    mediaType: "image",
    mediaSrc: "",
    targetUrl: "/VOXExporter",
    categories: ["Computational Design", "Software Development"],
  },
  {
    title: "CTEP",
    description: "Modular Robotic System",
    mediaType: "image",
    mediaSrc: "/projects/CTEP/images/ViewCapture20211227_131540.png",
    targetUrl: "/CTEP",
    categories: ["Computational Design", "Software Development"],
  },
];
export default projects;
